/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Visoris API
 * API de autenticação e sessões do Visoris.
 *
 * O fluxo de autenticação é baseado em cookies HttpOnly:
 * 1. `POST /api/v1/auth/register` ou `POST /api/v1/auth/login` → recebe os cookies `baseToken` e `refreshToken`.
 * 2. `POST /api/v1/auth/workspace` com o `baseToken` + `refreshToken` → recebe o `accessToken` e um novo `refreshToken`.
 * 3. `POST /api/v1/auth/refresh` com o `refreshToken` → renova `accessToken` e `refreshToken`.
 * 4. `POST /api/v1/auth/logout` com o `refreshToken` → revoga o token e limpa os cookies de sessão.
 *
 * Todos os tokens são transportados exclusivamente via cookies. Para testar no Swagger UI,
 * faça login/registro e copie os valores dos cookies de resposta para a seção Authorize.
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  AuthLogin200,
  AuthLogin400,
  AuthLogin401,
  AuthLogin500,
  AuthLogout200,
  AuthLogout500,
  AuthMe200,
  AuthMe401,
  AuthMe500,
  AuthRefresh200,
  AuthRefresh401,
  AuthRefresh500,
  AuthRegister201,
  AuthRegister400,
  AuthRegister409,
  AuthRegister500,
  AuthSelectWorkspace200,
  AuthSelectWorkspace400,
  AuthSelectWorkspace401,
  AuthSelectWorkspace403,
  AuthSelectWorkspace500,
  LoginRequest,
  RegisterRequest,
  WorkspaceRequest,
} from '../index.schemas';

import { customInstance } from '../../lib/axios';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type authLoginResponse200 = {
  data: AuthLogin200;
  status: 200;
};

export type authLoginResponse400 = {
  data: AuthLogin400;
  status: 400;
};

export type authLoginResponse401 = {
  data: AuthLogin401;
  status: 401;
};

export type authLoginResponse500 = {
  data: AuthLogin500;
  status: 500;
};

export type authLoginResponseSuccess = authLoginResponse200 & {
  headers: Headers;
};
export type authLoginResponseError = (
  authLoginResponse400 | authLoginResponse401 | authLoginResponse500
) & {
  headers: Headers;
};

export type authLoginResponse = authLoginResponseSuccess | authLoginResponseError;

export const getAuthLoginUrl = () => {
  return `/api/v1/auth/login`;
};

/**
 * Valida as credenciais do usuário. Em caso de sucesso retorna os dados do usuário e a lista de
 * workspaces (clínicas) dos quais ele é membro, além de definir os cookies `baseToken`
 * (300s) e `refreshToken` (7 dias).
 *
 * O `baseToken` deve ser enviado na rota POST /api/v1/auth/workspace para selecionar um workspace
 * e obter o `accessToken`. Falhas de autenticação retornam sempre a mesma mensagem genérica
 * "Credenciais inválidas." para não revelar quais credenciais estão incorretas.
 * @summary Autentica um usuário e inicia uma sessão parcial (Base Token).
 */
export const authLogin = async (
  loginRequest: LoginRequest,
  options?: Parameters<typeof customInstance>[1],
): Promise<authLoginResponse> => {
  return customInstance<authLoginResponse>(getAuthLoginUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(loginRequest),
  });
};

export const getAuthLoginMutationOptions = <
  TError = AuthLogin400 | AuthLogin401 | AuthLogin500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authLogin>>,
    TError,
    { data: LoginRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authLogin>>,
  TError,
  { data: LoginRequest },
  TContext
> => {
  const mutationKey = ['authLogin'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authLogin>>,
    { data: LoginRequest }
  > = (props) => {
    const { data } = props ?? {};

    return authLogin(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof authLogin>>>;
export type AuthLoginMutationBody = LoginRequest;
export type AuthLoginMutationError = AuthLogin400 | AuthLogin401 | AuthLogin500;

/**
 * @summary Autentica um usuário e inicia uma sessão parcial (Base Token).
 */
export const useAuthLogin = <
  TError = AuthLogin400 | AuthLogin401 | AuthLogin500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authLogin>>,
      TError,
      { data: LoginRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authLogin>>,
  TError,
  { data: LoginRequest },
  TContext
> => {
  return useMutation(getAuthLoginMutationOptions(options), queryClient);
};
export type authRefreshResponse200 = {
  data: AuthRefresh200;
  status: 200;
};

export type authRefreshResponse401 = {
  data: AuthRefresh401;
  status: 401;
};

export type authRefreshResponse500 = {
  data: AuthRefresh500;
  status: 500;
};

export type authRefreshResponseSuccess = authRefreshResponse200 & {
  headers: Headers;
};
export type authRefreshResponseError = (authRefreshResponse401 | authRefreshResponse500) & {
  headers: Headers;
};

export type authRefreshResponse = authRefreshResponseSuccess | authRefreshResponseError;

export const getAuthRefreshUrl = () => {
  return `/api/v1/auth/refresh`;
};

/**
 * Rotaciona o `refreshToken` recebido via cookie e emite um novo `accessToken` + novo `refreshToken`.
 * O refresh token antigo é revogado imediatamente (single-use). Não possui corpo de requisição.
 * @summary Renova a sessão usando o refresh token (cookie).
 */
export const authRefresh = async (
  options?: Parameters<typeof customInstance>[1],
): Promise<authRefreshResponse> => {
  return customInstance<authRefreshResponse>(getAuthRefreshUrl(), {
    ...options,
    method: 'POST',
  });
};

export const getAuthRefreshMutationOptions = <
  TError = AuthRefresh401 | AuthRefresh500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof authRefresh>>, TError, void, TContext>;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<Awaited<ReturnType<typeof authRefresh>>, TError, void, TContext> => {
  const mutationKey = ['authRefresh'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof authRefresh>>, void> = () => {
    return authRefresh(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthRefreshMutationResult = NonNullable<Awaited<ReturnType<typeof authRefresh>>>;

export type AuthRefreshMutationError = AuthRefresh401 | AuthRefresh500;

/**
 * @summary Renova a sessão usando o refresh token (cookie).
 */
export const useAuthRefresh = <TError = AuthRefresh401 | AuthRefresh500, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof authRefresh>>, TError, void, TContext>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof authRefresh>>, TError, void, TContext> => {
  return useMutation(getAuthRefreshMutationOptions(options), queryClient);
};
export type authRegisterResponse201 = {
  data: AuthRegister201;
  status: 201;
};

export type authRegisterResponse400 = {
  data: AuthRegister400;
  status: 400;
};

export type authRegisterResponse409 = {
  data: AuthRegister409;
  status: 409;
};

export type authRegisterResponse500 = {
  data: AuthRegister500;
  status: 500;
};

export type authRegisterResponseSuccess = authRegisterResponse201 & {
  headers: Headers;
};
export type authRegisterResponseError = (
  authRegisterResponse400 | authRegisterResponse409 | authRegisterResponse500
) & {
  headers: Headers;
};

export type authRegisterResponse = authRegisterResponseSuccess | authRegisterResponseError;

export const getAuthRegisterUrl = () => {
  return `/api/v1/auth/register`;
};

/**
 * Cria a conta e já emite os cookies `baseToken` (300s) e `refreshToken` (7 dias).
 * A lista de workspaces da resposta é sempre vazia, pois o vínculo com clínicas é criado depois.
 *
 * Regras de validação:
 * - `fullName`, `email`, `password` e `professionalDocument` são obrigatórios (o documento pode vir `null`, mas não vazio).
 * - `email` deve ter formato válido e não ser de domínio descartável.
 * - `password` deve ter no mínimo 8 caracteres, conter maiúscula, minúscula, número e caractere especial, e apenas caracteres ASCII.
 * - Limites: `fullName` e `email` até 255 caracteres; `professionalDocument` até 50.
 * @summary Cria uma conta de usuário (DOCTOR) e inicia uma sessão parcial.
 */
export const authRegister = async (
  registerRequest: RegisterRequest,
  options?: Parameters<typeof customInstance>[1],
): Promise<authRegisterResponse> => {
  return customInstance<authRegisterResponse>(getAuthRegisterUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(registerRequest),
  });
};

export const getAuthRegisterMutationOptions = <
  TError = AuthRegister400 | AuthRegister409 | AuthRegister500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authRegister>>,
    TError,
    { data: RegisterRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authRegister>>,
  TError,
  { data: RegisterRequest },
  TContext
> => {
  const mutationKey = ['authRegister'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authRegister>>,
    { data: RegisterRequest }
  > = (props) => {
    const { data } = props ?? {};

    return authRegister(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof authRegister>>>;
export type AuthRegisterMutationBody = RegisterRequest;
export type AuthRegisterMutationError = AuthRegister400 | AuthRegister409 | AuthRegister500;

/**
 * @summary Cria uma conta de usuário (DOCTOR) e inicia uma sessão parcial.
 */
export const useAuthRegister = <
  TError = AuthRegister400 | AuthRegister409 | AuthRegister500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authRegister>>,
      TError,
      { data: RegisterRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authRegister>>,
  TError,
  { data: RegisterRequest },
  TContext
> => {
  return useMutation(getAuthRegisterMutationOptions(options), queryClient);
};
export type authSelectWorkspaceResponse200 = {
  data: AuthSelectWorkspace200;
  status: 200;
};

export type authSelectWorkspaceResponse400 = {
  data: AuthSelectWorkspace400;
  status: 400;
};

export type authSelectWorkspaceResponse401 = {
  data: AuthSelectWorkspace401;
  status: 401;
};

export type authSelectWorkspaceResponse403 = {
  data: AuthSelectWorkspace403;
  status: 403;
};

export type authSelectWorkspaceResponse500 = {
  data: AuthSelectWorkspace500;
  status: 500;
};

export type authSelectWorkspaceResponseSuccess = authSelectWorkspaceResponse200 & {
  headers: Headers;
};
export type authSelectWorkspaceResponseError = (
  | authSelectWorkspaceResponse400
  | authSelectWorkspaceResponse401
  | authSelectWorkspaceResponse403
  | authSelectWorkspaceResponse500
) & {
  headers: Headers;
};

export type authSelectWorkspaceResponse =
  authSelectWorkspaceResponseSuccess | authSelectWorkspaceResponseError;

export const getAuthSelectWorkspaceUrl = () => {
  return `/api/v1/auth/workspace`;
};

/**
 * Usa o `baseToken` (emitido em login/registro) e o `refreshToken` para escolher a clínica ativa.
 * Em caso de sucesso: emite `accessToken` (900s), rotaciona o `refreshToken` e invalida (blacklist)
 * o `baseToken` — o mesmo `baseToken` não pode ser reutilizado.
 *
 * O `clinicId` deve ser um número inteiro positivo correspondente a uma clínica da qual o usuário é membro.
 * @summary Seleciona o workspace (clínica) e emite o access token.
 */
export const authSelectWorkspace = async (
  workspaceRequest: WorkspaceRequest,
  options?: Parameters<typeof customInstance>[1],
): Promise<authSelectWorkspaceResponse> => {
  return customInstance<authSelectWorkspaceResponse>(getAuthSelectWorkspaceUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(workspaceRequest),
  });
};

export const getAuthSelectWorkspaceMutationOptions = <
  TError =
    | AuthSelectWorkspace400
    | AuthSelectWorkspace401
    | AuthSelectWorkspace403
    | AuthSelectWorkspace500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authSelectWorkspace>>,
    TError,
    { data: WorkspaceRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authSelectWorkspace>>,
  TError,
  { data: WorkspaceRequest },
  TContext
> => {
  const mutationKey = ['authSelectWorkspace'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authSelectWorkspace>>,
    { data: WorkspaceRequest }
  > = (props) => {
    const { data } = props ?? {};

    return authSelectWorkspace(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthSelectWorkspaceMutationResult = NonNullable<
  Awaited<ReturnType<typeof authSelectWorkspace>>
>;
export type AuthSelectWorkspaceMutationBody = WorkspaceRequest;
export type AuthSelectWorkspaceMutationError =
  AuthSelectWorkspace400 | AuthSelectWorkspace401 | AuthSelectWorkspace403 | AuthSelectWorkspace500;

/**
 * @summary Seleciona o workspace (clínica) e emite o access token.
 */
export const useAuthSelectWorkspace = <
  TError =
    | AuthSelectWorkspace400
    | AuthSelectWorkspace401
    | AuthSelectWorkspace403
    | AuthSelectWorkspace500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authSelectWorkspace>>,
      TError,
      { data: WorkspaceRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authSelectWorkspace>>,
  TError,
  { data: WorkspaceRequest },
  TContext
> => {
  return useMutation(getAuthSelectWorkspaceMutationOptions(options), queryClient);
};
export type authMeResponse200 = {
  data: AuthMe200;
  status: 200;
};

export type authMeResponse401 = {
  data: AuthMe401;
  status: 401;
};

export type authMeResponse500 = {
  data: AuthMe500;
  status: 500;
};

export type authMeResponseSuccess = authMeResponse200 & {
  headers: Headers;
};
export type authMeResponseError = (authMeResponse401 | authMeResponse500) & {
  headers: Headers;
};

export type authMeResponse = authMeResponseSuccess | authMeResponseError;

export const getAuthMeUrl = () => {
  return `/api/v1/auth/me`;
};

/**
 * Retorna o usuário autenticado e seus workspaces a partir dos cookies.
 * Se o `accessToken` for válido, a sessão é retornada diretamente. Caso contrário,
 * tenta rotacionar a sessão usando o `refreshToken` (emitindo novos cookies `accessToken`
 * e `refreshToken`) antes de retornar os dados.
 * @summary Restaura a sessão do usuário autenticado.
 */
export const authMe = async (
  options?: Parameters<typeof customInstance>[1],
): Promise<authMeResponse> => {
  return customInstance<authMeResponse>(getAuthMeUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getAuthMeQueryKey = () => {
  return [`/api/v1/auth/me`] as const;
};

export const getAuthMeQueryOptions = <
  TData = Awaited<ReturnType<typeof authMe>>,
  TError = AuthMe401 | AuthMe500,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData>>;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAuthMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof authMe>>> = ({ signal }) =>
    authMe({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof authMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AuthMeQueryResult = NonNullable<Awaited<ReturnType<typeof authMe>>>;
export type AuthMeQueryError = AuthMe401 | AuthMe500;

export function useAuthMe<
  TData = Awaited<ReturnType<typeof authMe>>,
  TError = AuthMe401 | AuthMe500,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authMe>>,
          TError,
          Awaited<ReturnType<typeof authMe>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAuthMe<
  TData = Awaited<ReturnType<typeof authMe>>,
  TError = AuthMe401 | AuthMe500,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authMe>>,
          TError,
          Awaited<ReturnType<typeof authMe>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAuthMe<
  TData = Awaited<ReturnType<typeof authMe>>,
  TError = AuthMe401 | AuthMe500,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Restaura a sessão do usuário autenticado.
 */

export function useAuthMe<
  TData = Awaited<ReturnType<typeof authMe>>,
  TError = AuthMe401 | AuthMe500,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof authMe>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAuthMeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export type authLogoutResponse200 = {
  data: AuthLogout200;
  status: 200;
};

export type authLogoutResponse500 = {
  data: AuthLogout500;
  status: 500;
};

export type authLogoutResponseSuccess = authLogoutResponse200 & {
  headers: Headers;
};
export type authLogoutResponseError = authLogoutResponse500 & {
  headers: Headers;
};

export type authLogoutResponse = authLogoutResponseSuccess | authLogoutResponseError;

export const getAuthLogoutUrl = () => {
  return `/api/v1/auth/logout`;
};

/**
 * Revoga o `refreshToken` recebido via cookie e limpa os cookies `accessToken`, `refreshToken`
 * e `baseToken` (Max-Age=0). Não possui corpo de requisição e é idempotente: cookies ausentes,
 * desconhecidos ou já revogados ainda retornam 200.
 * @summary Encerra a sessão atual e limpa os cookies de sessão.
 */
export const authLogout = async (
  options?: Parameters<typeof customInstance>[1],
): Promise<authLogoutResponse> => {
  return customInstance<authLogoutResponse>(getAuthLogoutUrl(), {
    ...options,
    method: 'POST',
  });
};

export const getAuthLogoutMutationOptions = <TError = AuthLogout500, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof authLogout>>, TError, void, TContext>;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<Awaited<ReturnType<typeof authLogout>>, TError, void, TContext> => {
  const mutationKey = ['authLogout'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof authLogout>>, void> = () => {
    return authLogout(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof authLogout>>>;

export type AuthLogoutMutationError = AuthLogout500;

/**
 * @summary Encerra a sessão atual e limpa os cookies de sessão.
 */
export const useAuthLogout = <TError = AuthLogout500, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof authLogout>>, TError, void, TContext>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof authLogout>>, TError, void, TContext> => {
  return useMutation(getAuthLogoutMutationOptions(options), queryClient);
};
