/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Visoris API
 * API de autenticação e sessões do Visoris.
 *
 * O fluxo de autenticação é baseado em cookies HttpOnly:
 * 1. `POST /api/v1/auth/register` ou `POST /api/v1/auth/login` → recebe os cookies `accessToken` e `refreshToken`.
 * 2. `POST /api/v1/auth/refresh` com o `refreshToken` → renova `accessToken` e `refreshToken`.
 * 3. `POST /api/v1/auth/logout` com o `refreshToken` → revoga o token e limpa os cookies de sessão.
 *
 * Todos os tokens são transportados exclusivamente via cookies. Para testar no Swagger UI,
 * faça login/registro e copie os valores dos cookies de resposta para a seção Authorize.
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  ClinicsCreate200,
  ClinicsCreate201,
  ClinicsCreate400,
  ClinicsCreate401,
  ClinicsCreate500,
  ClinicsList200,
  ClinicsList401,
  ClinicsList500,
  CreateClinicRequest,
} from '../index.schemas';

import { customInstance } from '../../lib/axios';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type clinicsListResponse200 = {
  data: ClinicsList200;
  status: 200;
};

export type clinicsListResponse401 = {
  data: ClinicsList401;
  status: 401;
};

export type clinicsListResponse500 = {
  data: ClinicsList500;
  status: 500;
};

export type clinicsListResponseSuccess = clinicsListResponse200 & {
  headers: Headers;
};
export type clinicsListResponseError = (clinicsListResponse401 | clinicsListResponse500) & {
  headers: Headers;
};

export type clinicsListResponse = clinicsListResponseSuccess | clinicsListResponseError;

export const getClinicsListUrl = () => {
  return `/api/v1/clinics`;
};

/**
 * Retorna somente as clínicas vinculadas ao usuário autenticado (JOIN entre
 * `clinics` e `doctor_clinics` via `user_id`). Nunca retorna clínicas de outros
 * usuários. Retorna uma lista vazia quando não há vínculos.
 * @summary Lista as clínicas vinculadas ao usuário autenticado.
 */
export const clinicsList = async (
  options?: Parameters<typeof customInstance>[1],
): Promise<clinicsListResponse> => {
  return customInstance<clinicsListResponse>(getClinicsListUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getClinicsListQueryKey = () => {
  return [`/api/v1/clinics`] as const;
};

export const getClinicsListQueryOptions = <
  TData = Awaited<ReturnType<typeof clinicsList>>,
  TError = ClinicsList401 | ClinicsList500,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof clinicsList>>, TError, TData>>;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getClinicsListQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof clinicsList>>> = ({ signal }) =>
    clinicsList({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof clinicsList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ClinicsListQueryResult = NonNullable<Awaited<ReturnType<typeof clinicsList>>>;
export type ClinicsListQueryError = ClinicsList401 | ClinicsList500;

export function useClinicsList<
  TData = Awaited<ReturnType<typeof clinicsList>>,
  TError = ClinicsList401 | ClinicsList500,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof clinicsList>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof clinicsList>>,
          TError,
          Awaited<ReturnType<typeof clinicsList>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useClinicsList<
  TData = Awaited<ReturnType<typeof clinicsList>>,
  TError = ClinicsList401 | ClinicsList500,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof clinicsList>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof clinicsList>>,
          TError,
          Awaited<ReturnType<typeof clinicsList>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useClinicsList<
  TData = Awaited<ReturnType<typeof clinicsList>>,
  TError = ClinicsList401 | ClinicsList500,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof clinicsList>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Lista as clínicas vinculadas ao usuário autenticado.
 */

export function useClinicsList<
  TData = Awaited<ReturnType<typeof clinicsList>>,
  TError = ClinicsList401 | ClinicsList500,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof clinicsList>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getClinicsListQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export type clinicsCreateResponse200 = {
  data: ClinicsCreate200;
  status: 200;
};

export type clinicsCreateResponse201 = {
  data: ClinicsCreate201;
  status: 201;
};

export type clinicsCreateResponse400 = {
  data: ClinicsCreate400;
  status: 400;
};

export type clinicsCreateResponse401 = {
  data: ClinicsCreate401;
  status: 401;
};

export type clinicsCreateResponse500 = {
  data: ClinicsCreate500;
  status: 500;
};

export type clinicsCreateResponseSuccess = (clinicsCreateResponse200 | clinicsCreateResponse201) & {
  headers: Headers;
};
export type clinicsCreateResponseError = (
  clinicsCreateResponse400 | clinicsCreateResponse401 | clinicsCreateResponse500
) & {
  headers: Headers;
};

export type clinicsCreateResponse = clinicsCreateResponseSuccess | clinicsCreateResponseError;

export const getClinicsCreateUrl = () => {
  return `/api/v1/clinics`;
};

/**
 * Cria uma nova clínica e a vincula ao usuário autenticado, ou reutiliza uma clínica
 * existente identificada pelo CNPJ. Nunca duplica clínicas nem vínculos.
 *
 * Regras:
 * - `name` é obrigatório (não pode ser vazio, até 255 caracteres).
 * - `cnpj` é opcional; quando informado deve ter 14 dígitos e dígitos verificadores
 *   válidos (Módulo 11) e é normalizado para apenas dígitos.
 * - Quando o CNPJ corresponde a uma clínica existente, os campos `name`/`phone`/`address`
 *   enviados são ignorados e o vínculo é criado (ou mantido) de forma idempotente.
 * - Retorna HTTP 201 quando a clínica é criada e HTTP 200 quando uma clínica existente
 *   é reutilizada/vinculada.
 * @summary Registra ou vincula uma clínica ao usuário autenticado.
 */
export const clinicsCreate = async (
  createClinicRequest: CreateClinicRequest,
  options?: Parameters<typeof customInstance>[1],
): Promise<clinicsCreateResponse> => {
  return customInstance<clinicsCreateResponse>(getClinicsCreateUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createClinicRequest),
  });
};

export const getClinicsCreateMutationOptions = <
  TError = ClinicsCreate400 | ClinicsCreate401 | ClinicsCreate500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof clinicsCreate>>,
    TError,
    { data: CreateClinicRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof clinicsCreate>>,
  TError,
  { data: CreateClinicRequest },
  TContext
> => {
  const mutationKey = ['clinicsCreate'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof clinicsCreate>>,
    { data: CreateClinicRequest }
  > = (props) => {
    const { data } = props ?? {};

    return clinicsCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ClinicsCreateMutationResult = NonNullable<Awaited<ReturnType<typeof clinicsCreate>>>;
export type ClinicsCreateMutationBody = CreateClinicRequest;
export type ClinicsCreateMutationError = ClinicsCreate400 | ClinicsCreate401 | ClinicsCreate500;

/**
 * @summary Registra ou vincula uma clínica ao usuário autenticado.
 */
export const useClinicsCreate = <
  TError = ClinicsCreate400 | ClinicsCreate401 | ClinicsCreate500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof clinicsCreate>>,
      TError,
      { data: CreateClinicRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof clinicsCreate>>,
  TError,
  { data: CreateClinicRequest },
  TContext
> => {
  return useMutation(getClinicsCreateMutationOptions(options), queryClient);
};
