/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Visoris API
 * API de autenticação e sessões do Visoris.
 *
 * O fluxo de autenticação é baseado em cookies HttpOnly:
 * 1. `POST /api/v1/auth/register` ou `POST /api/v1/auth/login` → recebe os cookies `accessToken` e `refreshToken`.
 * 2. `POST /api/v1/auth/refresh` com o `refreshToken` → renova `accessToken` e `refreshToken`.
 * 3. `POST /api/v1/auth/logout` com o `refreshToken` → revoga o token e limpa os cookies de sessão.
 *
 * Todos os tokens são transportados exclusivamente via cookies. Para testar no Swagger UI,
 * faça login/registro e copie os valores dos cookies de resposta para a seção Authorize.
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  PatientRequest,
  PatientsCreate201,
  PatientsCreate400,
  PatientsCreate401,
  PatientsCreate404,
  PatientsCreate500,
  PatientsList200,
  PatientsList401,
  PatientsList404,
  PatientsList500,
  PatientsListParams,
} from '../index.schemas';

import { customInstance } from '../../lib/axios';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type patientsListResponse200 = {
  data: PatientsList200;
  status: 200;
};

export type patientsListResponse401 = {
  data: PatientsList401;
  status: 401;
};

export type patientsListResponse404 = {
  data: PatientsList404;
  status: 404;
};

export type patientsListResponse500 = {
  data: PatientsList500;
  status: 500;
};

export type patientsListResponseSuccess = patientsListResponse200 & {
  headers: Headers;
};
export type patientsListResponseError = (
  patientsListResponse401 | patientsListResponse404 | patientsListResponse500
) & {
  headers: Headers;
};

export type patientsListResponse = patientsListResponseSuccess | patientsListResponseError;

export const getPatientsListUrl = (params: PatientsListParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/patients?${stringifiedParams}`
    : `/api/v1/patients`;
};

/**
 * Retorna a lista de pacientes vinculados ao cliente informado. Requer que o cliente pertença a uma clínica do médico autenticado.
 * @summary Lista os pacientes vinculados a um tutor.
 */
export const patientsList = async (
  params: PatientsListParams,
  options?: Parameters<typeof customInstance>[1],
): Promise<patientsListResponse> => {
  return customInstance<patientsListResponse>(getPatientsListUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getPatientsListQueryKey = (params?: PatientsListParams) => {
  return [`/api/v1/patients`, ...(params ? [params] : [])] as const;
};

export const getPatientsListQueryOptions = <
  TData = Awaited<ReturnType<typeof patientsList>>,
  TError = PatientsList401 | PatientsList404 | PatientsList500,
>(
  params: PatientsListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof patientsList>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPatientsListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof patientsList>>> = ({ signal }) =>
    patientsList(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof patientsList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PatientsListQueryResult = NonNullable<Awaited<ReturnType<typeof patientsList>>>;
export type PatientsListQueryError = PatientsList401 | PatientsList404 | PatientsList500;

export function usePatientsList<
  TData = Awaited<ReturnType<typeof patientsList>>,
  TError = PatientsList401 | PatientsList404 | PatientsList500,
>(
  params: PatientsListParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof patientsList>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof patientsList>>,
          TError,
          Awaited<ReturnType<typeof patientsList>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePatientsList<
  TData = Awaited<ReturnType<typeof patientsList>>,
  TError = PatientsList401 | PatientsList404 | PatientsList500,
>(
  params: PatientsListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof patientsList>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof patientsList>>,
          TError,
          Awaited<ReturnType<typeof patientsList>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePatientsList<
  TData = Awaited<ReturnType<typeof patientsList>>,
  TError = PatientsList401 | PatientsList404 | PatientsList500,
>(
  params: PatientsListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof patientsList>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Lista os pacientes vinculados a um tutor.
 */

export function usePatientsList<
  TData = Awaited<ReturnType<typeof patientsList>>,
  TError = PatientsList401 | PatientsList404 | PatientsList500,
>(
  params: PatientsListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof patientsList>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPatientsListQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export type patientsCreateResponse201 = {
  data: PatientsCreate201;
  status: 201;
};

export type patientsCreateResponse400 = {
  data: PatientsCreate400;
  status: 400;
};

export type patientsCreateResponse401 = {
  data: PatientsCreate401;
  status: 401;
};

export type patientsCreateResponse404 = {
  data: PatientsCreate404;
  status: 404;
};

export type patientsCreateResponse500 = {
  data: PatientsCreate500;
  status: 500;
};

export type patientsCreateResponseSuccess = patientsCreateResponse201 & {
  headers: Headers;
};
export type patientsCreateResponseError = (
  | patientsCreateResponse400
  | patientsCreateResponse401
  | patientsCreateResponse404
  | patientsCreateResponse500
) & {
  headers: Headers;
};

export type patientsCreateResponse = patientsCreateResponseSuccess | patientsCreateResponseError;

export const getPatientsCreateUrl = () => {
  return `/api/v1/patients`;
};

/**
 * Cadastra o paciente (PET ou HUMAN) com detalhes biológicos livres em JSON.
 * @summary Cadastra um novo paciente vinculado a um tutor.
 */
export const patientsCreate = async (
  patientRequest: PatientRequest,
  options?: Parameters<typeof customInstance>[1],
): Promise<patientsCreateResponse> => {
  return customInstance<patientsCreateResponse>(getPatientsCreateUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(patientRequest),
  });
};

export const getPatientsCreateMutationOptions = <
  TError = PatientsCreate400 | PatientsCreate401 | PatientsCreate404 | PatientsCreate500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patientsCreate>>,
    TError,
    { data: PatientRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof patientsCreate>>,
  TError,
  { data: PatientRequest },
  TContext
> => {
  const mutationKey = ['patientsCreate'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patientsCreate>>,
    { data: PatientRequest }
  > = (props) => {
    const { data } = props ?? {};

    return patientsCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PatientsCreateMutationResult = NonNullable<Awaited<ReturnType<typeof patientsCreate>>>;
export type PatientsCreateMutationBody = PatientRequest;
export type PatientsCreateMutationError =
  PatientsCreate400 | PatientsCreate401 | PatientsCreate404 | PatientsCreate500;

/**
 * @summary Cadastra um novo paciente vinculado a um tutor.
 */
export const usePatientsCreate = <
  TError = PatientsCreate400 | PatientsCreate401 | PatientsCreate404 | PatientsCreate500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof patientsCreate>>,
      TError,
      { data: PatientRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof patientsCreate>>,
  TError,
  { data: PatientRequest },
  TContext
> => {
  return useMutation(getPatientsCreateMutationOptions(options), queryClient);
};
