/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Visoris API
 * API de autenticação e sessões do Visoris.
 *
 * O fluxo de autenticação é baseado em cookies HttpOnly:
 * 1. `POST /api/v1/auth/register` ou `POST /api/v1/auth/login` → recebe os cookies `baseToken` e `refreshToken`.
 * 2. `POST /api/v1/auth/workspace` com o `baseToken` + `refreshToken` → recebe o `accessToken` e um novo `refreshToken`.
 * 3. `POST /api/v1/auth/refresh` com o `refreshToken` → renova `accessToken` e `refreshToken`.
 * 4. `POST /api/v1/auth/logout` com o `refreshToken` → revoga o token e limpa os cookies de sessão.
 *
 * Todos os tokens são transportados exclusivamente via cookies. Para testar no Swagger UI,
 * faça login/registro e copie os valores dos cookies de resposta para a seção Authorize.
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 */
export interface LoginRequest {
  /** E-mail do usuário (não pode ser vazio e deve ter formato válido). */
  email: string;
  /** Senha do usuário (não pode ser vazia). */
  password: string;
}

export interface RegisterRequest {
  fullName: string;
  email: string;
  password: string;
  /** @nullable */
  professionalDocument?: string | null;
}

export interface WorkspaceRequest {
  /**
   * ID da clínica (Snowflake). Deve ser um número inteiro positivo.
   * @pattern ^[1-9][0-9]*$
   */
  clinicId: string;
}

export interface UserData {
  /** ID do usuário (Snowflake). */
  id: string;
  fullName: string;
  /** @nullable */
  professionalDocument?: string | null;
}

export interface WorkspaceData {
  /** ID da clínica (Snowflake). */
  clinicId: string;
  name: string;
  role: string;
}

export interface LoginResponse {
  user: UserData;
  workspaces: WorkspaceData[];
}

export interface RegisterResponse {
  user: UserData;
  workspaces: string[];
}

export interface ActiveWorkspace {
  /** ID da clínica (Snowflake). */
  clinicId: string;
  name: string;
  role: string;
}

export interface WorkspaceResponse {
  activeWorkspace: ActiveWorkspace;
}

export interface RefreshResponse {
  /** Validade do access token em segundos. */
  expiresIn: number;
}

export interface ValidationError {
  /** Nome do campo que falhou na validação. */
  field: string;
  /** Mensagem de erro do campo. */
  message: string;
}

export type AuthLogin200 = {
  erro: boolean;
  message: string;
  data: LoginResponse;
  httpcode: number;
  timestamp: string;
};

export type AuthLogin400 =
  | {
      erro: boolean;
      message: string;
      /** @nullable */
      data: { [key: string]: unknown } | null;
      httpcode: number;
      timestamp: string;
    }
  | {
      erro: boolean;
      message: string;
      data: {
        errors: ValidationError[];
      };
      httpcode: number;
      timestamp: string;
    };

/**
 * @nullable
 */
export type AuthLogin401Data = { [key: string]: unknown } | null;

export type AuthLogin401 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: AuthLogin401Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type AuthLogin500Data = { [key: string]: unknown } | null;

export type AuthLogin500 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: AuthLogin500Data;
  httpcode: number;
  timestamp: string;
};

export type AuthRefresh200 = {
  erro: boolean;
  message: string;
  data: RefreshResponse;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type AuthRefresh401Data = { [key: string]: unknown } | null;

export type AuthRefresh401 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: AuthRefresh401Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type AuthRefresh500Data = { [key: string]: unknown } | null;

export type AuthRefresh500 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: AuthRefresh500Data;
  httpcode: number;
  timestamp: string;
};

export type AuthRegister201 = {
  erro: boolean;
  message: string;
  data: RegisterResponse;
  httpcode: number;
  timestamp: string;
};

export type AuthRegister400 =
  | {
      erro: boolean;
      message: string;
      /** @nullable */
      data: { [key: string]: unknown } | null;
      httpcode: number;
      timestamp: string;
    }
  | {
      erro: boolean;
      message: string;
      data: {
        errors: ValidationError[];
      };
      httpcode: number;
      timestamp: string;
    };

/**
 * @nullable
 */
export type AuthRegister409Data = { [key: string]: unknown } | null;

export type AuthRegister409 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: AuthRegister409Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type AuthRegister500Data = { [key: string]: unknown } | null;

export type AuthRegister500 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: AuthRegister500Data;
  httpcode: number;
  timestamp: string;
};

export type AuthSelectWorkspace200 = {
  erro: boolean;
  message: string;
  data: WorkspaceResponse;
  httpcode: number;
  timestamp: string;
};

export type AuthSelectWorkspace400 =
  | {
      erro: boolean;
      message: string;
      /** @nullable */
      data: { [key: string]: unknown } | null;
      httpcode: number;
      timestamp: string;
    }
  | {
      erro: boolean;
      message: string;
      data: {
        errors: ValidationError[];
      };
      httpcode: number;
      timestamp: string;
    };

/**
 * @nullable
 */
export type AuthSelectWorkspace401Data = { [key: string]: unknown } | null;

export type AuthSelectWorkspace401 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: AuthSelectWorkspace401Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type AuthSelectWorkspace403Data = { [key: string]: unknown } | null;

export type AuthSelectWorkspace403 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: AuthSelectWorkspace403Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type AuthSelectWorkspace500Data = { [key: string]: unknown } | null;

export type AuthSelectWorkspace500 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: AuthSelectWorkspace500Data;
  httpcode: number;
  timestamp: string;
};

export type AuthMe200 = {
  erro: boolean;
  message: string;
  data: LoginResponse;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type AuthMe401Data = { [key: string]: unknown } | null;

export type AuthMe401 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: AuthMe401Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type AuthMe500Data = { [key: string]: unknown } | null;

export type AuthMe500 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: AuthMe500Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type AuthLogout200Data = { [key: string]: unknown } | null;

export type AuthLogout200 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: AuthLogout200Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type AuthLogout500Data = { [key: string]: unknown } | null;

export type AuthLogout500 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: AuthLogout500Data;
  httpcode: number;
  timestamp: string;
};
