/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Visoris API
 * API de autenticação e sessões do Visoris.
 *
 * O fluxo de autenticação é baseado em cookies HttpOnly:
 * 1. `POST /api/v1/auth/register` ou `POST /api/v1/auth/login` → recebe os cookies `accessToken` e `refreshToken`.
 * 2. `POST /api/v1/auth/refresh` com o `refreshToken` → renova `accessToken` e `refreshToken`.
 * 3. `POST /api/v1/auth/logout` com o `refreshToken` → revoga o token e limpa os cookies de sessão.
 *
 * Todos os tokens são transportados exclusivamente via cookies. Para testar no Swagger UI,
 * faça login/registro e copie os valores dos cookies de resposta para a seção Authorize.
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 */
export interface LoginRequest {
  /** E-mail do usuário (não pode ser vazio e deve ter formato válido). */
  email: string;
  /** Senha do usuário (não pode ser vazia). */
  password: string;
}

export interface RegisterRequest {
  fullName: string;
  email: string;
  password: string;
  /** @nullable */
  professionalDocument?: string | null;
}

export interface UserData {
  /** ID do usuário (Snowflake). */
  id: string;
  fullName: string;
  /** @nullable */
  professionalDocument?: string | null;
}

export interface LoginResponse {
  user: UserData;
}

export interface RegisterResponse {
  user: UserData;
}

export interface RefreshResponse {
  /** Validade do access token em segundos. */
  expiresIn: number;
}

export interface ValidationError {
  /** Nome do campo que falhou na validação. */
  field: string;
  /** Mensagem de erro do campo. */
  message: string;
}

export interface ClinicData {
  /** ID da clínica (Snowflake). */
  id: string;
  name: string;
  /** @nullable */
  cnpj?: string | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  address?: string | null;
}

export interface CreateClinicRequest {
  /** Nome da clínica (obrigatório, não pode ser vazio). */
  name: string;
  /**
   * CNPJ opcional. Deve ter 14 dígitos com dígitos verificadores válidos (Módulo 11); normalizado para apenas dígitos.
   * @nullable
   */
  cnpj?: string | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  address?: string | null;
}

export interface ClinicListResponse {
  clinics: ClinicData[];
}

export interface CreateClinicResponse {
  clinic: ClinicData;
}

export type AuthLogin200 = {
  erro: boolean;
  message: string;
  data: LoginResponse;
  httpcode: number;
  timestamp: string;
};

export type AuthLogin400 =
  | {
      erro: boolean;
      message: string;
      /** @nullable */
      data: { [key: string]: unknown } | null;
      httpcode: number;
      timestamp: string;
    }
  | {
      erro: boolean;
      message: string;
      data: {
        errors: ValidationError[];
      };
      httpcode: number;
      timestamp: string;
    };

/**
 * @nullable
 */
export type AuthLogin401Data = { [key: string]: unknown } | null;

export type AuthLogin401 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: AuthLogin401Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type AuthLogin500Data = { [key: string]: unknown } | null;

export type AuthLogin500 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: AuthLogin500Data;
  httpcode: number;
  timestamp: string;
};

export type AuthRefresh200 = {
  erro: boolean;
  message: string;
  data: RefreshResponse;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type AuthRefresh401Data = { [key: string]: unknown } | null;

export type AuthRefresh401 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: AuthRefresh401Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type AuthRefresh500Data = { [key: string]: unknown } | null;

export type AuthRefresh500 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: AuthRefresh500Data;
  httpcode: number;
  timestamp: string;
};

export type AuthRegister201 = {
  erro: boolean;
  message: string;
  data: RegisterResponse;
  httpcode: number;
  timestamp: string;
};

export type AuthRegister400 =
  | {
      erro: boolean;
      message: string;
      /** @nullable */
      data: { [key: string]: unknown } | null;
      httpcode: number;
      timestamp: string;
    }
  | {
      erro: boolean;
      message: string;
      data: {
        errors: ValidationError[];
      };
      httpcode: number;
      timestamp: string;
    };

/**
 * @nullable
 */
export type AuthRegister409Data = { [key: string]: unknown } | null;

export type AuthRegister409 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: AuthRegister409Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type AuthRegister500Data = { [key: string]: unknown } | null;

export type AuthRegister500 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: AuthRegister500Data;
  httpcode: number;
  timestamp: string;
};

export type AuthMe200 = {
  erro: boolean;
  message: string;
  data: LoginResponse;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type AuthMe401Data = { [key: string]: unknown } | null;

export type AuthMe401 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: AuthMe401Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type AuthMe500Data = { [key: string]: unknown } | null;

export type AuthMe500 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: AuthMe500Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type AuthLogout200Data = { [key: string]: unknown } | null;

export type AuthLogout200 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: AuthLogout200Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type AuthLogout500Data = { [key: string]: unknown } | null;

export type AuthLogout500 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: AuthLogout500Data;
  httpcode: number;
  timestamp: string;
};

export type ClinicsList200 = {
  erro: boolean;
  message: string;
  data: ClinicListResponse;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type ClinicsList401Data = { [key: string]: unknown } | null;

export type ClinicsList401 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: ClinicsList401Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type ClinicsList500Data = { [key: string]: unknown } | null;

export type ClinicsList500 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: ClinicsList500Data;
  httpcode: number;
  timestamp: string;
};

export type ClinicsCreate200 = {
  erro: boolean;
  message: string;
  data: CreateClinicResponse;
  httpcode: number;
  timestamp: string;
};

export type ClinicsCreate201 = {
  erro: boolean;
  message: string;
  data: CreateClinicResponse;
  httpcode: number;
  timestamp: string;
};

export type ClinicsCreate400 =
  | {
      erro: boolean;
      message: string;
      /** @nullable */
      data: { [key: string]: unknown } | null;
      httpcode: number;
      timestamp: string;
    }
  | {
      erro: boolean;
      message: string;
      data: {
        errors: ValidationError[];
      };
      httpcode: number;
      timestamp: string;
    };

/**
 * @nullable
 */
export type ClinicsCreate401Data = { [key: string]: unknown } | null;

export type ClinicsCreate401 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: ClinicsCreate401Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type ClinicsCreate500Data = { [key: string]: unknown } | null;

export type ClinicsCreate500 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: ClinicsCreate500Data;
  httpcode: number;
  timestamp: string;
};
