/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Visoris API
 * API de autenticação e sessões do Visoris.
 *
 * O fluxo de autenticação é baseado em cookies HttpOnly:
 * 1. `POST /api/v1/auth/register` ou `POST /api/v1/auth/login` → recebe os cookies `accessToken` e `refreshToken`.
 * 2. `POST /api/v1/auth/refresh` com o `refreshToken` → renova `accessToken` e `refreshToken`.
 * 3. `POST /api/v1/auth/logout` com o `refreshToken` → revoga o token e limpa os cookies de sessão.
 *
 * Todos os tokens são transportados exclusivamente via cookies. Para testar no Swagger UI,
 * faça login/registro e copie os valores dos cookies de resposta para a seção Authorize.
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 */
export interface LoginRequest {
  /** E-mail do usuário (não pode ser vazio e deve ter formato válido). */
  email: string;
  /** Senha do usuário (não pode ser vazia). */
  password: string;
}

export interface RegisterRequest {
  fullName: string;
  email: string;
  password: string;
  /** @nullable */
  professionalDocument?: string | null;
}

export interface UserData {
  /** ID do usuário (Snowflake). */
  id: string;
  fullName: string;
  /** @nullable */
  professionalDocument?: string | null;
}

export interface LoginResponse {
  user: UserData;
}

export interface RegisterResponse {
  user: UserData;
}

export interface RefreshResponse {
  /** Validade do access token em segundos. */
  expiresIn: number;
}

export interface ValidationError {
  /** Nome do campo que falhou na validação. */
  field: string;
  /** Mensagem de erro do campo. */
  message: string;
}

export interface ClinicData {
  /** ID da clínica (Snowflake). */
  id: string;
  name: string;
  /** @nullable */
  cnpj?: string | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  address?: string | null;
}

export interface CreateClinicRequest {
  /**
   * Nome da clínica (obrigatório, mínimo 2, máximo 255 caracteres).
   * @minLength 2
   * @maxLength 255
   */
  name: string;
  /**
   * CNPJ opcional. Exatamente 14 dígitos com dígitos verificadores válidos (Módulo 11); normalizado para apenas dígitos.
   * @nullable
   * @pattern ^\d{14}$
   */
  cnpj?: string | null;
  /**
   * Telefone opcional com 10 ou 11 dígitos (DDD + número), normalizado para dígitos puros.
   * @nullable
   * @pattern ^\d{10,11}$
   */
  phone?: string | null;
  /**
   * Endereço opcional, máximo de 500 caracteres.
   * @maxLength 500
   * @nullable
   */
  address?: string | null;
}

export interface ClinicListResponse {
  clinics: ClinicData[];
}

export interface CreateClinicResponse {
  clinic: ClinicData;
}

export interface ClientRequest {
  /** Nome completo do tutor. */
  full_name: string;
  /** CPF do tutor (11 dígitos). */
  document_cpf: string;
  /** E-mail do tutor. */
  email: string;
  /** Telefone de contato do tutor. */
  phone: string;
}

export interface CreateClientResponse {
  /** ID do cliente gerado (Snowflake). */
  id: string;
}

export interface ClientResponse {
  /** ID do cliente (Snowflake). */
  id: string;
  /** ID do usuário logado. */
  userId: string;
  fullName: string;
  /** @nullable */
  documentCpf?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  phone?: string | null;
  createdAt: string;
}

export interface ClientListResponse {
  clients: ClientResponse[];
}

/**
 * Tipo de paciente (PET ou HUMAN).
 */
export type PatientRequestPatientType =
  (typeof PatientRequestPatientType)[keyof typeof PatientRequestPatientType];

export const PatientRequestPatientType = {
  PET: 'PET',
  HUMAN: 'HUMAN',
} as const;

/**
 * Detalhes biológicos livres em formato JSON.
 */
export type PatientRequestBiologicalDetails = { [key: string]: unknown };

export interface PatientRequest {
  /** ID do tutor/cliente (Snowflake). */
  client_id: number;
  /** Nome do paciente. */
  name: string;
  /** Tipo de paciente (PET ou HUMAN). */
  patient_type: PatientRequestPatientType;
  /** Data de nascimento (YYYY-MM-DD). */
  birth_date: string;
  /** Detalhes biológicos livres em formato JSON. */
  biological_details: PatientRequestBiologicalDetails;
}

export type PatientResponsePatientType =
  (typeof PatientResponsePatientType)[keyof typeof PatientResponsePatientType];

export const PatientResponsePatientType = {
  PET: 'PET',
  HUMAN: 'HUMAN',
} as const;

export type PatientResponseBiologicalDetails = { [key: string]: unknown };

export interface PatientResponse {
  /** ID do paciente (Snowflake). */
  id: string;
  /** @nullable */
  clientId?: string | null;
  name: string;
  patientType: PatientResponsePatientType;
  /** @nullable */
  birthDate?: string | null;
  biologicalDetails: PatientResponseBiologicalDetails;
  createdAt: string;
}

export interface CreatePatientResponse {
  patient: PatientResponse;
}

export interface PatientListResponse {
  patients: PatientResponse[];
}

/**
 * Tipo de paciente (PET ou HUMAN).
 */
export type UpdatePatientRequestPatientType =
  (typeof UpdatePatientRequestPatientType)[keyof typeof UpdatePatientRequestPatientType];

export const UpdatePatientRequestPatientType = {
  PET: 'PET',
  HUMAN: 'HUMAN',
} as const;

/**
 * Detalhes biológicos livres em formato JSON (raça, pelagem, idade, etc.).
 */
export type UpdatePatientRequestBiologicalDetails = { [key: string]: unknown };

export interface UpdatePatientRequest {
  /** Nome do paciente. */
  name: string;
  /** Tipo de paciente (PET ou HUMAN). */
  patient_type: UpdatePatientRequestPatientType;
  /**
   * Data de nascimento (YYYY-MM-DD).
   * @nullable
   */
  birth_date?: string | null;
  /** Detalhes biológicos livres em formato JSON (raça, pelagem, idade, etc.). */
  biological_details: UpdatePatientRequestBiologicalDetails;
}

export type AuthLogin200 = {
  erro: boolean;
  message: string;
  data: LoginResponse;
  httpcode: number;
  timestamp: string;
};

export type AuthLogin400 =
  | {
      erro: boolean;
      message: string;
      /** @nullable */
      data: { [key: string]: unknown } | null;
      httpcode: number;
      timestamp: string;
    }
  | {
      erro: boolean;
      message: string;
      data: {
        errors: ValidationError[];
      };
      httpcode: number;
      timestamp: string;
    };

/**
 * @nullable
 */
export type AuthLogin401Data = { [key: string]: unknown } | null;

export type AuthLogin401 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: AuthLogin401Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type AuthLogin500Data = { [key: string]: unknown } | null;

export type AuthLogin500 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: AuthLogin500Data;
  httpcode: number;
  timestamp: string;
};

export type AuthRefresh200 = {
  erro: boolean;
  message: string;
  data: RefreshResponse;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type AuthRefresh401Data = { [key: string]: unknown } | null;

export type AuthRefresh401 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: AuthRefresh401Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type AuthRefresh500Data = { [key: string]: unknown } | null;

export type AuthRefresh500 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: AuthRefresh500Data;
  httpcode: number;
  timestamp: string;
};

export type AuthRegister201 = {
  erro: boolean;
  message: string;
  data: RegisterResponse;
  httpcode: number;
  timestamp: string;
};

export type AuthRegister400 =
  | {
      erro: boolean;
      message: string;
      /** @nullable */
      data: { [key: string]: unknown } | null;
      httpcode: number;
      timestamp: string;
    }
  | {
      erro: boolean;
      message: string;
      data: {
        errors: ValidationError[];
      };
      httpcode: number;
      timestamp: string;
    };

/**
 * @nullable
 */
export type AuthRegister409Data = { [key: string]: unknown } | null;

export type AuthRegister409 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: AuthRegister409Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type AuthRegister500Data = { [key: string]: unknown } | null;

export type AuthRegister500 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: AuthRegister500Data;
  httpcode: number;
  timestamp: string;
};

export type AuthMe200 = {
  erro: boolean;
  message: string;
  data: LoginResponse;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type AuthMe401Data = { [key: string]: unknown } | null;

export type AuthMe401 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: AuthMe401Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type AuthMe500Data = { [key: string]: unknown } | null;

export type AuthMe500 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: AuthMe500Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type AuthLogout200Data = { [key: string]: unknown } | null;

export type AuthLogout200 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: AuthLogout200Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type AuthLogout500Data = { [key: string]: unknown } | null;

export type AuthLogout500 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: AuthLogout500Data;
  httpcode: number;
  timestamp: string;
};

export type ClinicsList200 = {
  erro: boolean;
  message: string;
  data: ClinicListResponse;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type ClinicsList401Data = { [key: string]: unknown } | null;

export type ClinicsList401 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: ClinicsList401Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type ClinicsList500Data = { [key: string]: unknown } | null;

export type ClinicsList500 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: ClinicsList500Data;
  httpcode: number;
  timestamp: string;
};

export type ClinicsCreate200 = {
  erro: boolean;
  message: string;
  data: CreateClinicResponse;
  httpcode: number;
  timestamp: string;
};

export type ClinicsCreate201 = {
  erro: boolean;
  message: string;
  data: CreateClinicResponse;
  httpcode: number;
  timestamp: string;
};

export type ClinicsCreate400 =
  | {
      erro: boolean;
      message: string;
      /** @nullable */
      data: { [key: string]: unknown } | null;
      httpcode: number;
      timestamp: string;
    }
  | {
      erro: boolean;
      message: string;
      data: {
        errors: ValidationError[];
      };
      httpcode: number;
      timestamp: string;
    };

/**
 * @nullable
 */
export type ClinicsCreate401Data = { [key: string]: unknown } | null;

export type ClinicsCreate401 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: ClinicsCreate401Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type ClinicsCreate500Data = { [key: string]: unknown } | null;

export type ClinicsCreate500 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: ClinicsCreate500Data;
  httpcode: number;
  timestamp: string;
};

export type ClientsListParams = {
  limit?: number;
  offset?: number;
};

export type ClientsList200 = {
  erro: boolean;
  message: string;
  data: ClientListResponse;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type ClientsList401Data = { [key: string]: unknown } | null;

export type ClientsList401 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: ClientsList401Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type ClientsList404Data = { [key: string]: unknown } | null;

export type ClientsList404 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: ClientsList404Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type ClientsList500Data = { [key: string]: unknown } | null;

export type ClientsList500 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: ClientsList500Data;
  httpcode: number;
  timestamp: string;
};

export type ClientsCreate201 = {
  erro: boolean;
  message: string;
  data: CreateClientResponse;
  httpcode: number;
  timestamp: string;
};

export type ClientsCreate400 =
  | {
      erro: boolean;
      message: string;
      /** @nullable */
      data: { [key: string]: unknown } | null;
      httpcode: number;
      timestamp: string;
    }
  | {
      erro: boolean;
      message: string;
      data: {
        errors: ValidationError[];
      };
      httpcode: number;
      timestamp: string;
    };

/**
 * @nullable
 */
export type ClientsCreate401Data = { [key: string]: unknown } | null;

export type ClientsCreate401 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: ClientsCreate401Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type ClientsCreate404Data = { [key: string]: unknown } | null;

export type ClientsCreate404 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: ClientsCreate404Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type ClientsCreate409Data = { [key: string]: unknown } | null;

export type ClientsCreate409 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: ClientsCreate409Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type ClientsCreate500Data = { [key: string]: unknown } | null;

export type ClientsCreate500 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: ClientsCreate500Data;
  httpcode: number;
  timestamp: string;
};

export type ClientsUpdate200 = {
  erro: boolean;
  message: string;
  data: ClientResponse;
  httpcode: number;
  timestamp: string;
};

export type ClientsUpdate400 =
  | {
      erro: boolean;
      message: string;
      /** @nullable */
      data: { [key: string]: unknown } | null;
      httpcode: number;
      timestamp: string;
    }
  | {
      erro: boolean;
      message: string;
      data: {
        errors: ValidationError[];
      };
      httpcode: number;
      timestamp: string;
    };

/**
 * @nullable
 */
export type ClientsUpdate401Data = { [key: string]: unknown } | null;

export type ClientsUpdate401 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: ClientsUpdate401Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type ClientsUpdate404Data = { [key: string]: unknown } | null;

export type ClientsUpdate404 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: ClientsUpdate404Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type ClientsUpdate409Data = { [key: string]: unknown } | null;

export type ClientsUpdate409 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: ClientsUpdate409Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type ClientsUpdate500Data = { [key: string]: unknown } | null;

export type ClientsUpdate500 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: ClientsUpdate500Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type ClientsDelete200Data = { [key: string]: unknown } | null;

export type ClientsDelete200 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: ClientsDelete200Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type ClientsDelete401Data = { [key: string]: unknown } | null;

export type ClientsDelete401 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: ClientsDelete401Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type ClientsDelete404Data = { [key: string]: unknown } | null;

export type ClientsDelete404 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: ClientsDelete404Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type ClientsDelete409Data = { [key: string]: unknown } | null;

export type ClientsDelete409 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: ClientsDelete409Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type ClientsDelete500Data = { [key: string]: unknown } | null;

export type ClientsDelete500 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: ClientsDelete500Data;
  httpcode: number;
  timestamp: string;
};

export type PatientsListParams = {
  /**
   * ID do cliente/tutor.
   */
  clientId: number;
  limit?: number;
  offset?: number;
};

export type PatientsList200 = {
  erro: boolean;
  message: string;
  data: PatientListResponse;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type PatientsList401Data = { [key: string]: unknown } | null;

export type PatientsList401 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: PatientsList401Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type PatientsList404Data = { [key: string]: unknown } | null;

export type PatientsList404 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: PatientsList404Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type PatientsList500Data = { [key: string]: unknown } | null;

export type PatientsList500 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: PatientsList500Data;
  httpcode: number;
  timestamp: string;
};

export type PatientsCreate201 = {
  erro: boolean;
  message: string;
  data: CreatePatientResponse;
  httpcode: number;
  timestamp: string;
};

export type PatientsCreate400 =
  | {
      erro: boolean;
      message: string;
      /** @nullable */
      data: { [key: string]: unknown } | null;
      httpcode: number;
      timestamp: string;
    }
  | {
      erro: boolean;
      message: string;
      data: {
        errors: ValidationError[];
      };
      httpcode: number;
      timestamp: string;
    };

/**
 * @nullable
 */
export type PatientsCreate401Data = { [key: string]: unknown } | null;

export type PatientsCreate401 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: PatientsCreate401Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type PatientsCreate404Data = { [key: string]: unknown } | null;

export type PatientsCreate404 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: PatientsCreate404Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type PatientsCreate500Data = { [key: string]: unknown } | null;

export type PatientsCreate500 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: PatientsCreate500Data;
  httpcode: number;
  timestamp: string;
};

export type PatientsUpdate200 = {
  erro: boolean;
  message: string;
  data: PatientResponse;
  httpcode: number;
  timestamp: string;
};

export type PatientsUpdate400 =
  | {
      erro: boolean;
      message: string;
      /** @nullable */
      data: { [key: string]: unknown } | null;
      httpcode: number;
      timestamp: string;
    }
  | {
      erro: boolean;
      message: string;
      data: {
        errors: ValidationError[];
      };
      httpcode: number;
      timestamp: string;
    };

/**
 * @nullable
 */
export type PatientsUpdate401Data = { [key: string]: unknown } | null;

export type PatientsUpdate401 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: PatientsUpdate401Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type PatientsUpdate404Data = { [key: string]: unknown } | null;

export type PatientsUpdate404 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: PatientsUpdate404Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type PatientsUpdate500Data = { [key: string]: unknown } | null;

export type PatientsUpdate500 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: PatientsUpdate500Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type PatientsDelete200Data = { [key: string]: unknown } | null;

export type PatientsDelete200 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: PatientsDelete200Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type PatientsDelete401Data = { [key: string]: unknown } | null;

export type PatientsDelete401 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: PatientsDelete401Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type PatientsDelete404Data = { [key: string]: unknown } | null;

export type PatientsDelete404 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: PatientsDelete404Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type PatientsDelete409Data = { [key: string]: unknown } | null;

export type PatientsDelete409 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: PatientsDelete409Data;
  httpcode: number;
  timestamp: string;
};

/**
 * @nullable
 */
export type PatientsDelete500Data = { [key: string]: unknown } | null;

export type PatientsDelete500 = {
  erro: boolean;
  message: string;
  /** @nullable */
  data: PatientsDelete500Data;
  httpcode: number;
  timestamp: string;
};
