/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Visoris API
 * API de autenticação e sessões do Visoris.
 *
 * O fluxo de autenticação é baseado em cookies HttpOnly:
 * 1. `POST /api/v1/auth/register` ou `POST /api/v1/auth/login` → recebe os cookies `accessToken` e `refreshToken`.
 * 2. `POST /api/v1/auth/refresh` com o `refreshToken` → renova `accessToken` e `refreshToken`.
 * 3. `POST /api/v1/auth/logout` com o `refreshToken` → revoga o token e limpa os cookies de sessão.
 *
 * Todos os tokens são transportados exclusivamente via cookies. Para testar no Swagger UI,
 * faça login/registro e copie os valores dos cookies de resposta para a seção Authorize.
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  ClientRequest,
  ClientsCreate201,
  ClientsCreate400,
  ClientsCreate401,
  ClientsCreate404,
  ClientsCreate409,
  ClientsCreate500,
  ClientsDelete200,
  ClientsDelete401,
  ClientsDelete404,
  ClientsDelete409,
  ClientsDelete500,
  ClientsList200,
  ClientsList401,
  ClientsList404,
  ClientsList500,
  ClientsListParams,
  ClientsUpdate200,
  ClientsUpdate400,
  ClientsUpdate401,
  ClientsUpdate404,
  ClientsUpdate409,
  ClientsUpdate500,
} from '../index.schemas';

import { customInstance } from '../../lib/axios';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type clientsListResponse200 = {
  data: ClientsList200;
  status: 200;
};

export type clientsListResponse401 = {
  data: ClientsList401;
  status: 401;
};

export type clientsListResponse404 = {
  data: ClientsList404;
  status: 404;
};

export type clientsListResponse500 = {
  data: ClientsList500;
  status: 500;
};

export type clientsListResponseSuccess = clientsListResponse200 & {
  headers: Headers;
};
export type clientsListResponseError = (
  clientsListResponse401 | clientsListResponse404 | clientsListResponse500
) & {
  headers: Headers;
};

export type clientsListResponse = clientsListResponseSuccess | clientsListResponseError;

export const getClientsListUrl = (params?: ClientsListParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/clients?${stringifiedParams}` : `/api/v1/clients`;
};

/**
 * Retorna a lista paginada de tutores do usuário autenticado.
 * @summary Lista os tutores/clientes vinculados ao usuário logado.
 */
export const clientsList = async (
  params?: ClientsListParams,
  options?: Parameters<typeof customInstance>[1],
): Promise<clientsListResponse> => {
  return customInstance<clientsListResponse>(getClientsListUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getClientsListQueryKey = (params?: ClientsListParams) => {
  return [`/api/v1/clients`, ...(params ? [params] : [])] as const;
};

export const getClientsListQueryOptions = <
  TData = Awaited<ReturnType<typeof clientsList>>,
  TError = ClientsList401 | ClientsList404 | ClientsList500,
>(
  params?: ClientsListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof clientsList>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getClientsListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof clientsList>>> = ({ signal }) =>
    clientsList(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof clientsList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ClientsListQueryResult = NonNullable<Awaited<ReturnType<typeof clientsList>>>;
export type ClientsListQueryError = ClientsList401 | ClientsList404 | ClientsList500;

export function useClientsList<
  TData = Awaited<ReturnType<typeof clientsList>>,
  TError = ClientsList401 | ClientsList404 | ClientsList500,
>(
  params: undefined | ClientsListParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof clientsList>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof clientsList>>,
          TError,
          Awaited<ReturnType<typeof clientsList>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useClientsList<
  TData = Awaited<ReturnType<typeof clientsList>>,
  TError = ClientsList401 | ClientsList404 | ClientsList500,
>(
  params?: ClientsListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof clientsList>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof clientsList>>,
          TError,
          Awaited<ReturnType<typeof clientsList>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useClientsList<
  TData = Awaited<ReturnType<typeof clientsList>>,
  TError = ClientsList401 | ClientsList404 | ClientsList500,
>(
  params?: ClientsListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof clientsList>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Lista os tutores/clientes vinculados ao usuário logado.
 */

export function useClientsList<
  TData = Awaited<ReturnType<typeof clientsList>>,
  TError = ClientsList401 | ClientsList404 | ClientsList500,
>(
  params?: ClientsListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof clientsList>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getClientsListQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export type clientsCreateResponse201 = {
  data: ClientsCreate201;
  status: 201;
};

export type clientsCreateResponse400 = {
  data: ClientsCreate400;
  status: 400;
};

export type clientsCreateResponse401 = {
  data: ClientsCreate401;
  status: 401;
};

export type clientsCreateResponse404 = {
  data: ClientsCreate404;
  status: 404;
};

export type clientsCreateResponse409 = {
  data: ClientsCreate409;
  status: 409;
};

export type clientsCreateResponse500 = {
  data: ClientsCreate500;
  status: 500;
};

export type clientsCreateResponseSuccess = clientsCreateResponse201 & {
  headers: Headers;
};
export type clientsCreateResponseError = (
  | clientsCreateResponse400
  | clientsCreateResponse401
  | clientsCreateResponse404
  | clientsCreateResponse409
  | clientsCreateResponse500
) & {
  headers: Headers;
};

export type clientsCreateResponse = clientsCreateResponseSuccess | clientsCreateResponseError;

export const getClientsCreateUrl = () => {
  return `/api/v1/clients`;
};

/**
 * Cadastra o cliente e retorna o ID gerado.
 * @summary Cadastra um novo tutor/cliente vinculado ao usuário logado.
 */
export const clientsCreate = async (
  clientRequest: ClientRequest,
  options?: Parameters<typeof customInstance>[1],
): Promise<clientsCreateResponse> => {
  return customInstance<clientsCreateResponse>(getClientsCreateUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(clientRequest),
  });
};

export const getClientsCreateMutationOptions = <
  TError =
    ClientsCreate400 | ClientsCreate401 | ClientsCreate404 | ClientsCreate409 | ClientsCreate500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof clientsCreate>>,
    TError,
    { data: ClientRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof clientsCreate>>,
  TError,
  { data: ClientRequest },
  TContext
> => {
  const mutationKey = ['clientsCreate'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof clientsCreate>>,
    { data: ClientRequest }
  > = (props) => {
    const { data } = props ?? {};

    return clientsCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ClientsCreateMutationResult = NonNullable<Awaited<ReturnType<typeof clientsCreate>>>;
export type ClientsCreateMutationBody = ClientRequest;
export type ClientsCreateMutationError =
  ClientsCreate400 | ClientsCreate401 | ClientsCreate404 | ClientsCreate409 | ClientsCreate500;

/**
 * @summary Cadastra um novo tutor/cliente vinculado ao usuário logado.
 */
export const useClientsCreate = <
  TError =
    ClientsCreate400 | ClientsCreate401 | ClientsCreate404 | ClientsCreate409 | ClientsCreate500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof clientsCreate>>,
      TError,
      { data: ClientRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof clientsCreate>>,
  TError,
  { data: ClientRequest },
  TContext
> => {
  return useMutation(getClientsCreateMutationOptions(options), queryClient);
};
export type clientsUpdateResponse200 = {
  data: ClientsUpdate200;
  status: 200;
};

export type clientsUpdateResponse400 = {
  data: ClientsUpdate400;
  status: 400;
};

export type clientsUpdateResponse401 = {
  data: ClientsUpdate401;
  status: 401;
};

export type clientsUpdateResponse404 = {
  data: ClientsUpdate404;
  status: 404;
};

export type clientsUpdateResponse409 = {
  data: ClientsUpdate409;
  status: 409;
};

export type clientsUpdateResponse500 = {
  data: ClientsUpdate500;
  status: 500;
};

export type clientsUpdateResponseSuccess = clientsUpdateResponse200 & {
  headers: Headers;
};
export type clientsUpdateResponseError = (
  | clientsUpdateResponse400
  | clientsUpdateResponse401
  | clientsUpdateResponse404
  | clientsUpdateResponse409
  | clientsUpdateResponse500
) & {
  headers: Headers;
};

export type clientsUpdateResponse = clientsUpdateResponseSuccess | clientsUpdateResponseError;

export const getClientsUpdateUrl = (id: number) => {
  return `/api/v1/clients/${id}`;
};

/**
 * Atualiza as informações do tutor pertencente ao usuário autenticado.
 * @summary Atualiza os dados de um tutor/cliente.
 */
export const clientsUpdate = async (
  id: number,
  clientRequest: ClientRequest,
  options?: Parameters<typeof customInstance>[1],
): Promise<clientsUpdateResponse> => {
  return customInstance<clientsUpdateResponse>(getClientsUpdateUrl(id), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(clientRequest),
  });
};

export const getClientsUpdateMutationOptions = <
  TError =
    ClientsUpdate400 | ClientsUpdate401 | ClientsUpdate404 | ClientsUpdate409 | ClientsUpdate500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof clientsUpdate>>,
    TError,
    { id: number; data: ClientRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof clientsUpdate>>,
  TError,
  { id: number; data: ClientRequest },
  TContext
> => {
  const mutationKey = ['clientsUpdate'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof clientsUpdate>>,
    { id: number; data: ClientRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return clientsUpdate(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ClientsUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof clientsUpdate>>>;
export type ClientsUpdateMutationBody = ClientRequest;
export type ClientsUpdateMutationError =
  ClientsUpdate400 | ClientsUpdate401 | ClientsUpdate404 | ClientsUpdate409 | ClientsUpdate500;

/**
 * @summary Atualiza os dados de um tutor/cliente.
 */
export const useClientsUpdate = <
  TError =
    ClientsUpdate400 | ClientsUpdate401 | ClientsUpdate404 | ClientsUpdate409 | ClientsUpdate500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof clientsUpdate>>,
      TError,
      { id: number; data: ClientRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof clientsUpdate>>,
  TError,
  { id: number; data: ClientRequest },
  TContext
> => {
  return useMutation(getClientsUpdateMutationOptions(options), queryClient);
};
export type clientsDeleteResponse200 = {
  data: ClientsDelete200;
  status: 200;
};

export type clientsDeleteResponse401 = {
  data: ClientsDelete401;
  status: 401;
};

export type clientsDeleteResponse404 = {
  data: ClientsDelete404;
  status: 404;
};

export type clientsDeleteResponse409 = {
  data: ClientsDelete409;
  status: 409;
};

export type clientsDeleteResponse500 = {
  data: ClientsDelete500;
  status: 500;
};

export type clientsDeleteResponseSuccess = clientsDeleteResponse200 & {
  headers: Headers;
};
export type clientsDeleteResponseError = (
  | clientsDeleteResponse401
  | clientsDeleteResponse404
  | clientsDeleteResponse409
  | clientsDeleteResponse500
) & {
  headers: Headers;
};

export type clientsDeleteResponse = clientsDeleteResponseSuccess | clientsDeleteResponseError;

export const getClientsDeleteUrl = (id: number) => {
  return `/api/v1/clients/${id}`;
};

/**
 * Remove um tutor vinculado ao usuário autenticado caso não haja pacientes vinculados.
 * @summary Exclui um tutor/cliente.
 */
export const clientsDelete = async (
  id: number,
  options?: Parameters<typeof customInstance>[1],
): Promise<clientsDeleteResponse> => {
  return customInstance<clientsDeleteResponse>(getClientsDeleteUrl(id), {
    ...options,
    method: 'DELETE',
  });
};

export const getClientsDeleteMutationOptions = <
  TError = ClientsDelete401 | ClientsDelete404 | ClientsDelete409 | ClientsDelete500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof clientsDelete>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof clientsDelete>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ['clientsDelete'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof clientsDelete>>, { id: number }> = (
    props,
  ) => {
    const { id } = props ?? {};

    return clientsDelete(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ClientsDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof clientsDelete>>>;

export type ClientsDeleteMutationError =
  ClientsDelete401 | ClientsDelete404 | ClientsDelete409 | ClientsDelete500;

/**
 * @summary Exclui um tutor/cliente.
 */
export const useClientsDelete = <
  TError = ClientsDelete401 | ClientsDelete404 | ClientsDelete409 | ClientsDelete500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof clientsDelete>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof clientsDelete>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getClientsDeleteMutationOptions(options), queryClient);
};
